name: build tf

on:
  push:
    branches:
      - main
    paths:
      - app/tf
  pull_request:
    branches:
      - main
    paths:
      - app/tf
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: test
      run: go test -v
      working-directory: app/tf
    - name: build
      run: go build -o artifacts/ -v
      working-directory: app/tf
    - name: ls
      run: ls
      working-directory: artifacts
