name: build tf

on:
  push:
    branches:
      - main
    paths:
      - 'app/tf'
  pull_request:
    branches:
      - main
    paths:
      - 'app/tf'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - run: go test
      working-directory: app/tf
    - run: go build -o ../../artifacts/tf
      working-directory: app/tf